### ISSUE TITLE
 자가진단 서버에서 간헐적으로 만료된 인증서를 보내주는 이슈

### ISSUE THREAD

**Issue by Sylvia3259** [kimcore/hcs.js#4]
```
(node:15957) UnhandledPromiseRejectionWarning: FetchError: request to https://hcs.eduro.go.kr/transkeyServlet failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/Users/sylvia/auto-self-check/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

간헐적으로 이렇게 인증이 만료되었다고 에러가 뜹니다. (처음 5명 정도까지는 잘 되다가 갑자기 에러가 납니다)
그리고 여러 번 해봤는데 transkeyServlet 뿐만 아니라 registerServey, v2/findUser, transkeyServlet?op=getInitTime 등 다양한 곳에서 같은 에러가 발생하네요.

버전도 1.1.8로 업데이트 했는데 왜 이런 건가요???

아래는 제 코드 일부입니다.
```
const test = async () => {
    const schools = await hcs.searchSchool('선린인터넷고등학교');
    const school = schools[0];

    for (const student of students) {
        console.log(`${student.name}님 자가진단을 시작합니다.`)

        const login = await hcs.login(school.endpoint, school.schoolCode, student.name, student.birthday);
        if (!login.success) {
            console.log('로그인에 실패했습니다.');
            continue;
        }
        if (login.agreementRequired)
            await hcs.updateAgreement(school.endpoint, login.token);

        const passwordExists = await hcs.passwordExists(school.endpoint, login.token);
        if (!passwordExists) {
            console.log('비밀번호가 존재하지 않습니다.');
            continue;
        }

        let token;
        const secondLogin = await hcs.secondLogin(school.endpoint, login.token, student.password);
        if (!secondLogin.success) {
            console.log('잘못된 비밀번호입니다.');
            continue;
        }
        else if (secondLogin.message) {
            console.log(secondLogin.message);
            continue;
        }
        token = secondLogin.token;

        const result = await hcs.registerSurvey(school.endpoint, token, {
            Q1: false,
            Q2: false,
            Q3: false,
        });

        console.log(`자가진단이 완료되었습니다. (${result.registeredAt})`);
    }

    console.log(``);
};

test().then();
```

학교 코드 검색 부분을 for 안으로 넣어봐도 같은 오류가 납니다.

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`
라고 쓰니까 작동하긴 하는데 그리 좋은 방법은 아닌 것 같네요
보다 근본적인 해결 방법이 없을까요?

**Comment by kimcore** [comment]
2.0.0 버전부터 기본 agent에 `rejectUnauthorized: false`를 추가함으로써 해결되었습니다.
