### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'failCnt') 오류

### ISSUE THREAD

**Issue by BlackREDf4** [kimcore/hcs.js#9]
```
/storage/emulated/0/loco/node_modules/hcs.js/dist/secondLogin.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
TypeError: Cannot read properties of undefined (reading 'failCnt')
    at /storage/emulated/0/loco/node_modules/hcs.js/dist/secondLogin.js:31:40
    at Generator.next (<anonymous>)
    at fulfilled (/storage/emulated/0/loco/node_modules/hcs.js/dist/secondLogin.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

 안드로이드 termux 0.118.0 환경에서 kimcore님의 라이브러리를 사용해 자가 검진을 시도했더니 위와 같은 오류가 발생하였습니다.

 failCnt라는 키워드만 보고 메모리와 관련된 문제라 짐작하였으나 termux는 자체적으로 충분히 필요한 만큼의 메모리를 불러와 사용한다는 내용을 접하고, 접근이 잘못 된 것 같아 라이브러리의 원작자이신 kimcore님께 오류에 대하여 여쭤보고자 이슈로 작성해봅니다.

**Comment by kimcore** [comment]
새학기를 앞두고 교육부 측에서 사용자 정보를 초기화하여 로그인이 불가한 것으로 확인됩니다. 혹시 첫번째 토큰을 저장해두고 사용하시나요? (hcs.login 메서드를 통해 얻는 토큰)

**Comment by BlackREDf4** [comment]
지금 몇 가지를 더 알아내었는데, 본 이슈와 연관된 내용이라 이 밑에 덧붙이겠습니다.

```
Bearer 0156DA8A6E5DCDFE8D82E2FC11971F6E4811EFD32B874DEF1509AB3328F8EF87A8F02261D34B9880944DFBB02A9F984B0B1F8C8602614922EC241ACFA2AF71CAFFBFE34837BCD64F0BB5C1E81258BFD29B08D9F7EADE544AEB6B2BCB7B606FDD2628C72334B39586583E2C72D0C27B649B3E6A8125512745CA773AA6DE6F5DB3E9A28F44B743F4D153083D955C76094FF7242B6CE03EE67E1744FE3561C4FFD5B615A7237044B7019CDD98B70DFC2A4A7AE56A112346FEDD20CD1B703A01FCC6CADB0C6CB05DCCCB45816CB1
{
  isError: true,
  statusCode: 252,
  errorCode: 1003,
  message: '비밀번호가 초기화 되었습니다.'
}
D:\Project\개인\자가진단 매크로\node_modules\hcs.js\dist\secondLogin.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
TypeError: Cannot read properties of undefined (reading 'failCnt')
    at D:\Project\개인\자가진단 매크로\node_modules\hcs.js\dist\secondLogin.js:34:40
    at Generator.next (<anonymous>)
    at fulfilled (D:\Project\개인\자가진단 매크로\node_modules\hcs.js\dist\secondLogin.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

설치된 hcs.js 라이브러리의 secondLogin.js를 약간 수정하여 response의 값을 console.log로 출력하도록 하자 나온 내용입니다.

`response['message'] !== "비밀번호를 다시한번더 입력해주세요"`
위 식에 의해 failCnt(지금은 failCnt에 대해서 정확히 알고 말하고 있는 겁니다. 처음에 코드를 살펴보지도 않고 이상한 말을 한 점 죄송합니다) 라는 값이 반환되지 않았음에도 조건식은 충족하여 존재하지 않은 failCnt라는 값을 사용하려 했기에 발생한 오류인 것 같습니다.

**Comment by BlackREDf4** [comment]
```
        const response = yield (0, request_1.default)('/v2/validatePassword', 'POST', data, endpoint, token);
        const success = typeof response == "string";
        const res = success ? {
            success: true, token: response
        } : (response['isError'] && response['message'] === "비밀번호를 다시한번더 입력해주세요" ? {
            success: false,
            failCount: response['data']['failCnt'] ? Number(response['data']['failCnt']) : 5,
            remainingMinutes: response['data']['remainMinutes'] ? Number(response['data']['remainMinutes']) : 0,
            message: response['message']
        } : {
            success: false,
            failCount: null,
            remainingMinutes: null,
            message: response['message']
        });
        return res;
```
임시로 secondLogin.js의 내용 중 반환 부분을 위와 같이 수정하였더니 message에 "비밀번호가 초기화 되었습니다."라는 값이 들어가고, 이전처럼 실행 도중 중단되지는 않았습니다

**Comment by kimcore** [comment]
보내주신 코드를 참고해 2.0.5 버전에서는 에러 메시지가 제대로 나오도록 수정하였습니다. 다만 termux에서 작동하지 않는 이유는 저도 잘 모르겠네요.. 혹시 지금은 작동하는지 확인해주실 수 있을까요?

**Comment by BlackREDf4** [comment]
지금은 제대로 작동하고 있습니다. termux에서도 환경의 차이가 아니라 위와 똑같은 이유로 에러가 발생했던 것으로 보입니다.

**Comment by MelodicRealm** [comment]
똑같은 오류가 발생해서 코멘트합니다.

secondLogin.js가 서버에서 받아오는 response의 형식이 바뀐듯합니다.
response에 전에는 `token`만 들어있었는데 이제는 `token`과 `pInfAgrmYn`을 포함하는 오브젝트로 바뀐 것 같습니다.

secondLogin.js의 26번째에서
```js
const success = typeof response == "string";
        if (success) {
            return {
                success: true, token: response
            };
        }```
를
```js
const success = typeof response.token == "string";
        if (success) {
            return {
                success: true, token: response.token
            };
        }```
으로 수정하니 정상작동합니다.
